# Generated by Django 5.2.6 on 2025-09-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicknotes', '0002_cliente_detallepedido_devolucion_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalle_pedidos',
        ),
        migrations.AlterModelTable(
            name='devolucion',
            table='devoluciones',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
